import { CoffeData } from '../contexts/PurchaseContext.interface'

export const coffes: CoffeData[] = [
  {
    id: 1,
    coffe: 'Expresso Tradicional',
    info: 'O tradicional café feito com água quente e grãos moídos',
    valor: 9.9,
    tags: ['TRADICIONAL'],
    img: 'expressoTradicional',
  },
  {
    id: 2,
    coffe: 'Expresso Americano',
    info: 'Expresso diluído, menos intenso que o tradicional',
    valor: 9.9,
    tags: ['TRADICIONAL'],
    img: 'expressoAmericano',
  },
  {
    id: 3,
    coffe: 'Expresso Cremoso',
    info: 'Café expresso tradicional com espuma cremosa',
    valor: 9.9,
    tags: ['TRADICIONAL'],
    img: 'expressoCremoso',
  },
  {
    id: 4,
    coffe: 'Expresso Gelado',
    info: 'Bebida preparada com café expresso e cubos de gelo',
    valor: 9.9,
    tags: ['TRADICIONAL', 'GELADO'],
    img: 'expressoGelado',
  },
  {
    id: 5,
    coffe: 'Café com Leite',
    info: 'Meio a meio de expresso tradicional com leite vaporizado',
    valor: 9.9,
    tags: ['TRADICIONAL', 'COM LEITE'],
    img: 'cafeComLeite',
  },
  {
    id: 6,
    coffe: 'Latte',
    info: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    valor: 9.9,
    tags: ['TRADICIONAL', 'COM LEITE'],
    img: 'latte',
  },
  {
    id: 7,
    coffe: 'Capuccino',
    info: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    valor: 9.9,
    tags: ['TRADICIONAL', 'COM LEITE'],
    img: 'capuccino',
  },
  {
    id: 8,
    coffe: 'Macchiato',
    info: 'Café expresso misturado com um pouco de leite quente e espuma',
    valor: 9.9,
    tags: ['TRADICIONAL', 'COM LEITE'],
    img: 'macciato',
  },
  {
    id: 9,
    coffe: 'Mocaccino',
    info: 'Café expresso com calda de chocolate, pouco leite e espuma',
    valor: 9.9,
    tags: ['TRADICIONAL', 'COM LEITE'],
    img: 'mocaccino',
  },
  {
    id: 10,
    coffe: 'Chocolate Quente',
    info: 'Bebida feita com chocolate dissolvido no leite quente e café',
    valor: 9.9,
    tags: ['ESPECIAL', 'COM LEITE'],
    img: 'chocolateQuente',
  },
  {
    id: 11,
    coffe: 'Cubano',
    info: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    valor: 9.9,
    tags: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    img: 'cubano',
  },
  {
    id: 12,
    coffe: 'Havaiano',
    info: 'Bebida adocicada preparada com café e leite de coco',
    valor: 9.9,
    tags: ['ESPECIAL'],
    img: 'havaiano',
  },
  {
    id: 13,
    coffe: 'Árabe',
    info: 'Bebida preparada com grãos de café árabe e especiarias',
    valor: 9.9,
    tags: ['ESPECIAL'],
    img: 'arabe',
  },
  {
    id: 14,
    coffe: 'Irlandês',
    info: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    valor: 9.9,
    tags: ['ESPECIAL', 'ALCOÓLICO'],
    img: 'irlandes',
  },
]
